# Generated by Django 5.2.4 on 2025-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=20)),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
